name: Alter RootFS

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: true
        default: 'false'
        type: choice
        options:
        - "true"
        - "false"
      version:
        description: 'OpenWrt version'
        required: true
        default: 'snapshot'
        type: string

env:
  TZ: Asia/Shanghai
  DEVICE_NAME: unknown
  FILE_DATE: unknown
  FIRMWARE: unknown

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Install ubi_reader
      run: |
        #sudo apt-get update
        sudo apt-get install -y mtd-utils
        sudo apt-get install linux-modules-extra-$(uname -r)
        sudo apt-get install squashfs-tools
        sudo apt-get install -y python3 python3-pip liblzo2-dev
        pip3 install ubi_reader
        #pip install binwalk
        
    - name: Download image from Git assets URL
      run: |
        IMAGE_URL="https://downloads.openwrt.org/releases/24.10.2/targets/qualcommax/ipq807x/openwrt-24.10.2-qualcommax-ipq807x-linksys_mx4200v1-squashfs-factory.bin"
        OUTPUT_FILENAME="downloaded_fw.img"
        curl -L -o "$OUTPUT_FILENAME" "$IMAGE_URL"
      shell: bash

    - name: Extract a part of the image using dd
      run: |
          dd if=downloaded_fw.img of=rootfs.ubi bs=512 skip=12288
          ls -lh rootfs.ubi
          ls -ld /mnt
          which ubireader_extract_files
          pwd
          #xxd rootfs.ubi |grep UBI
          ubireader_extract_images rootfs.ubi
          #ls -latR
          #xxd img-1750711236_vol-rootfs.ubifs |head
          sudo mkdir /mnt/mx4200_rootfs
          sudo chmod 777 /mnt/mx4200_rootfs
          cd /mnt/mx4200_rootfs
          cp ./ubifs-root/rootfs.ubi/img-1750711236_vol-rootfs.ubifs /mnt/mx4200_rootfs/
          unsquashfs -s img-1750711236_vol-rootfs.ubifs
          unsquashfs img-1750711236_vol-rootfs.ubifs
          cd squashfs-root
          ls -latR squashfs-root
      continue-on-error: true

    - name: Modify files
      run: |
          # Navigate to the extracted rootfs
          cd /mnt/mx4200_rootfs
          ls -latR
          sudo echo "This is a new file created by the GitHub Action." > new_file.txt
          ls -lh


    - name: Repack the UBI image
      run: |
          # Create a new UBIFS image from the modified files
          #cd /mnt
          #sudo mkfs.ubifs -r /mnt/mx4200_rootfs -m 16384 -e 2031616 -c 16 -o rootfs-new.ubi

          # Create the ubinize config file
          sudo cat << EOF > ubinize.cfg
          [rootfs]
          mode=ubi
          image=new_ubifs.img
          vol_id=0
          vol_type=dynamic
          vol_name=rootfs
          vol_flags=autoresize
          EOF

          # Create the final UBI image
          #sudo ubinize -o new_ubi.img -p 2097152 -m 16384 ubinize.cfg


    - name: Upload the extracted file as an artifact
      uses: actions/upload-artifact@v4
      with:
          name: updated-rootfs
          path: /mnt/mx4200_rootfs/img-1750711236_vol-rootfs.ubifs
