name: Mx4200 Build

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: true
        default: 'false'
        type: choice
        options:
        - "true"
        - "false"
      version:
        description: 'OpenWrt version'
        required: true
        default: 'snapshot'
        type: string

env:
  TZ: Asia/Shanghai
  DEVICE_NAME: unknown
  FILE_DATE: unknown
  FIRMWARE: unknown

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Prep the host for openwrt
      run: |
        sudo apt update
        sudo apt install build-essential clang flex bison g++ gawk \
              gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
              python3-setuptools rsync swig unzip zlib1g-dev file wget
        
    - name: Download image from Git assets URL
      run: |
        git clone https://github.com/openwrt/openwrt.git
        cd openwrt
        git pull
        git checkout openwrt-24.10
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        CONF_URL="https://downloads.openwrt.org/releases/24.10.2/targets/qualcommax/ipq807x/config.buildinfo"
        OUTPUT_FILENAME=".config"
        curl -L -o "$OUTPUT_FILENAME" "$CONF_URL"
        make defconfig download clean world
      shell: bash

    - name: Upload the extracted file as an artifact
      uses: actions/upload-artifact@v4
      with:
          name: updated-rootfs
          path: rootfs-new.ubi
