name: UBIFS Test

on: [push]

jobs:
  ubifs-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and tag Docker image
        run: docker build -t ubifs-test-image -f Dockerfile.ubifs .

      - name: Run container with privileged access
        # Run the container with the privileged flag
        run: docker run --privileged -v ${{ github.workspace }}:/workspace ubifs-test-image /workspace/.github/scripts/run-test.sh

