name: UBIFS Test

on:
   repository_dispatch:
   workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: true
        default: 'false'
        type: choice
        options:
        - "true"
        - "false"
      version:
        description: 'OpenWrt version'
        required: true
        default: 'snapshot'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get kernel version and download source from Launchpad
        id: get_kernel_source
        run: |
          export kernel_version=$(uname -r)
          echo "kernel_version=${kernel_version}" >> $GITHUB_OUTPUT

          export ub_series=$(echo "$kernel_version" | sed -E 's/.*-([a-z]+[0-9]+).*/\1/')
          export ub_version=$(echo "$kernel_version" | sed -E 's/.*-([a-z]+[0-9]+).*/linux-\1/')
          
          sudo apt-get update
          sudo apt-get install -y git
          
          cd /tmp
          git clone --depth 1 git://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/${ub_version}/+git/${ub_series} kernel_build

          echo "kernel_source_path=/tmp/kernel_build" >> $GITHUB_OUTPUT

      - name: Build and run privileged container
        run: |
          docker build -t ubifs-builder -f Dockerfile.ubifs .

          docker run --privileged \
            -v /lib/modules:/lib/modules \
            -v /usr/src:/usr/src \
            -v ${{ github.workspace }}:/workspace \
            -v ${{ steps.get_kernel_source.outputs.kernel_source_path }}:/usr/src/kernel_build \
            -w /workspace \
            ubifs-builder /bin/bash -c "
            set -e

            # Use the mounted kernel source
            export KERN_BUILD_DIR=/usr/src/kernel_build
            
            # Use 'make' with the correct arguments to specify the module location
            echo 'Building nandsim module...'
            make -C \"$KERN_BUILD_DIR\" M=\"/workspace/\" modules

            # The module file is now at /workspace/drivers/mtd/nand/raw/nandsim.ko
            insmod drivers/mtd/nand/raw/nandsim.ko

            if lsmod | grep nandsim; then
              echo 'nandsim module loaded successfully.'
            else
              echo 'Failed to load nandsim module.'
              exit 1
            fi

            modprobe mtdblock
            modprobe ubi
            echo 'Configuring nandsim and UBIFS...'
            flash_eraseall /dev/mtd0
            
            mkfs.ubifs -r . -m 2048 -e 126976 -c 1024 -o ubifs.img

            ubiattach /dev/ubi_ctrl -m 0
            ubimkvol /dev/ubi0 -N my_ubifs_volume -m

            mkdir -p /mnt/ubifs
            mount -t ubifs ubi0:my_ubifs_volume /mnt/ubifs

            echo 'UBIFS mounted at /mnt/ubifs.'
            ls -l /mnt/ubifs
          "

